# Generated by Django 3.0.5 on 2020-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200513_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
